services:
  db:
    image: postgres:14
    container_name: restaurant_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restaurant
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
